name: walmart_sales_forecasting
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12
  - numpy=1.25.2
  - cython
  - pandas=2.0.3
  - seaborn=0.13.1
  - matplotlib=3.7.1
  - statsmodels=0.14.2
  - scipy=1.11.4
  - scikit-learn=1.2.2
  - plotly=5.11.0
  - pyyaml
  - joblib
  - pip
  - pip:
      - prophet==1.1.5
      - tqdm==4.66.4